# Workflow to automatically merge pull requests when ready
# WARNING: Do not use this workflow if reviews are not required!

name: MS - Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: { }

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          git config --local user.email "thepolyteam.tech@gmail.com"
          git config --local user.name "Happy Poly Team Bot"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          MERGE_LABELS: "ready"
          MERGE_REMOVE_LABELS: "ready"
          MERGE_DELETE_BRANCH: true
          MERGE_DELETE_BRANCH_FILTER: "develop,master"
          GITHUB_TOKEN: "${{ secrets.ROBOT_TOKEN }}"
